language: c
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - autoconf
          - automake
          - libtool
          - guile-2.0-dev
          - liblapack-dev
          - libfftw3-dev
          - libhdf5-serial-dev
          - git
      script:
        - git clone https://github.com/stevengj/libctl
        - (cd libctl && git checkout 7d51710e63952d343ce8f241cf92b5cbfd5f1ada && sh autogen.sh --prefix=`pwd`/../local && make && make install)
        - sh autogen.sh
        - ./configure --enable-maintainer-mode --prefix=`pwd`/.local --with-libctl=`pwd`/.local CPPFLAGS=-I`pwd`/.local LDFLAGS=-L`pwd`/.local
        - make && make check && make install
        - rm -rf * ~/.local
    - os: osx
      install:
        - brew tap homebrew/science
        - brew update
        - brew install guile autoconf automake libtool fftw lapack libctl
      script:
        - sh autogen.sh --prefix=`pwd`/.local
        - make && make check && make install
        - rm -rf * ~/.local
