language: c
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - autoconf
          - automake
          - libtool
          - guile-2.0-dev
          - liblapack-dev
          - libfftw3-dev
          - libhdf5-serial-dev
          - libctl-dev
      script:
        - sh autogen.sh --prefix=`pwd`/.local
        - make && make check && make install
        - rm -rf * ~/.local
    - os: osx
      install:
        - brew tap homebrew/science
        - brew update
        - brew install guile autoconf automake libtool fftw lapack libctl
      script:
        - sh autogen.sh --prefix=`pwd`/.local
        - make && make check && make install
        - rm -rf * ~/.local
